# Avance 2 conexión con API Yelp

#### _En este avance nos conectaremos con la API de Yelp para encontrar los restaurantes más indicados para nuestra segmentación de clientes (realizada en el Avance 1)_

In [43]:
import pandas as pd
import requests
import numpy as np
import openpyxl
import matplotlib.pyplot as plt
import seaborn as sns

#### <span style="color:#00b6ff">**Incorporación de segmentación de clientes**</span>

In [44]:
#Incorporamos los resultados del EDA para lograr un análisis completo

df_clientes = pd.read_csv("Clientes_filtrados.csv")

print("Datos del avance 1 cargados en el avance 2")
display(df_clientes.head())

Datos del avance 1 cargados en el avance 2

,id_persona,nombre,apellido,edad,genero,ciudad_residencia,estrato_socioeconomico,frecuencia_visita,promedio_gasto_comida,ocio,consume_licor,preferencias_alimenticias,membresia_premium,tipo_de_pago_mas_usado,ingresos_mensuales,rango_etario
0,2550327378,Jackson,Gomez,31.0,Masculino,Miami,Alto,6,67.51,Sí,No,Vegetariano,Sí,Efectivo,6425,26-35
1,6170452916,Bruce,Young,55.0,Masculino,Miami,Muy Alto,5,119.85,Sí,No,Carnes,Sí,Efectivo,15844,46-60
2,8077451214,April,Franco,30.0,Femenino,Miami,Alto,5,68.46,No,Sí,Mariscos,No,Efectivo,7298,26-35
3,5655633608,Kayla,Young,76.0,Femenino,Miami,Muy Alto,9,106.66,Sí,No,Otro,Sí,App,17941,60+
4,1069937700,Stephanie,Miles,50.0,Femenino,Miami,Alto,5,55.31,Sí,No,Vegetariano,Sí,Tarjeta,5784,46-60

#### <span style="color:#00b6ff">**Conexión con la API de Yelp**</span>

In [45]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [46]:
#url de la API
api_url='https://api.yelp.com/v3/businesses/search'

#estos datos corresponden a una cuenta de usuario creada previamente
clientid='GWOCZh9-BmZxtdsAjr7Gug'
apikey='FHVvXoNmTXIl9DuxYis7AV5uLPujm9MLwrhgs5NgvCfaOxd3V6mxt6dQU8eEqYJiGxe816XATx7ufWjbMWqbV-2Uku1jxBJv8BGRC74NroLPl27PDQqs0tDixit-YHYx'
headers={'Authorization':'Bearer %s'%apikey}

#### _Los clientes segmentados corresponden a la ciudad de Miami, en este caso tomamos la misma ciudad de referencia_

In [47]:
ciudad = "Miami"

In [48]:
#Consultamos la API de Yelp para obtener información sobre los restaurantes de la ciudad de Miami

params={'term':'restaurants','location': ciudad,'limit':50}
response=requests.get(api_url,params=params,headers=headers)
data=response.json()
data

{'businesses': [{'id': 'K3ukx2e11xTRtYBU01dmrA',
   'alias': 'salty-flame-miami',
   'name': 'Salty Flame',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/_6wShTvzfucB5dxFZv4Mpg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/salty-flame-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 258,
   'categories': [{'alias': 'asianfusion', 'title': 'Asian Fusion'},
    {'alias': 'steak', 'title': 'Steakhouses'},
    {'alias': 'cocktailbars', 'title': 'Cocktail Bars'}],
   'rating': 4.3,
   'coordinates': {'latitude': 25.76022, 'longitude': -80.19267},
   'transactions': ['delivery', 'pickup'],
   'location': {'address1': '1414 Brickell Ave',
    'address2': None,
    'address3': '',
    'city': 'Miami',
    'zip_code': '33131',
    'country': 'US',
    'state': 'FL',
    'display_address': ['1414 Brickell Ave', 'Miami, FL 33131']},
   'phone': '+13055638972',
   'display_phone': '(305) 563-8972',
   'distance': 9568.050891007853},
  {'id': 'UXHxLN3DcDGI57uDIfCuJA',
   'alias': 'olds-havana-cuban-bar-and-cocina-miami',
   'name': "Old's Havana Cuban Bar & Cocina",
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/OyMD-xvBjobfDmDdBs2Jfw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/olds-havana-cuban-bar-and-cocina-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 3193,
   'categories': [{'alias': 'cuban', 'title': 'Cuban'},
    {'alias': 'bars', 'title': 'Bars'},
    {'alias': 'venues', 'title': 'Venues & Event Spaces'}],
   'rating': 4.4,
   'coordinates': {'latitude': 25.765607074496565,
    'longitude': -80.21921771559332},
   'transactions': ['pickup', 'restaurant_reservation'],
   'price': '$$',
   'location': {'address1': '1442 SW 8th St',
    'address2': '',
    'address3': None,
    'city': 'Miami',
    'zip_code': '33135',
    'country': 'US',
    'state': 'FL',
    'display_address': ['1442 SW 8th St', 'Miami, FL 33135']},
   'phone': '+17865182196',
   'display_phone': '(786) 518-2196',
   'distance': 7038.216305367002},
  {'id': 'oxtMfBGmVNE18pFVuw7lFg',
   'alias': 'fratellino-coral-gables-2',
   'name': 'Fratellino',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/OPS9ibIzgVyzcJ3ZyNf9IQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/fratellino-coral-gables-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 1899,
   'categories': [{'alias': 'italian', 'title': 'Italian'}],
   'rating': 4.8,
   'coordinates': {'latitude': 25.74917, 'longitude': -80.26011},
   'transactions': ['delivery', 'pickup', 'restaurant_reservation'],
   'price': '$$$',
   'location': {'address1': '264 Miracle Mile',
    'address2': '',
    'address3': '',
    'city': 'Coral Gables',
    'zip_code': '33134',
    'country': 'US',
    'state': 'FL',
    'display_address': ['264 Miracle Mile', 'Coral Gables, FL 33134']},
   'phone': '+17864520068',
   'display_phone': '(786) 452-0068',
   'distance': 2834.064936518243},
  {'id': 'ix8ifP1jQM9ektdVAs19sQ',
   'alias': 'crazy-about-you-miami-3',
   'name': 'Crazy About You',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/C8cICmnvi0GRzr4OIwg6vQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/crazy-about-you-miami-3?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 2883,
   'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
    {'alias': 'italian', 'title': 'Italian'},
    {'alias': 'spanish', 'title': 'Spanish'}],
   'rating': 4.2,
   'coordinates': {'latitude': 25.762015277335745,
    'longitude': -80.1889859201474},
   'transactions': ['delivery'],
   'price': '$$$',
   'location': {'address1': '1155 Brickell Bay Dr',
    'address2': 'Ste 101',
    'address3': '',
    'city': 'Miami',
    'zip_code': '33131',
    'country': 'US',
    'state': 'FL',
    'display_address': ['1155 Brickell Bay Dr', 'Ste 101', 'Miami, FL 33131']},
   'phone': '+13053774442',
   'display_phone': '(305) 377-4442',
   'distance': 9973.468955482575},
  {'id': 'WqIBKxRUPXH3NqTViAHLxQ',
   'alias': 'bayshore-club-bar-and-grill-miami',
   'name': 'Bayshore Club Bar & Grill',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/B7tTbJMlp7Dk6rpE4P3j5Q/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/bayshore-club-bar-and-grill-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 1039,
   'categories': [{'alias': 'seafood', 'title': 'Seafood'},
    {'alias': 'tradamerican', 'title': 'American'},
    {'alias': 'wine_bars', 'title': 'Wine Bars'}],
   'rating': 4.3,
   'coordinates': {'latitude': 25.72877375829567, 'longitude': -80.2341624},
   'transactions': [],
   'price': '$$$',
   'location': {'address1': '3391 Pan American Dr',
    'address2': None,
    'address3': None,
    'city': 'Miami',
    'zip_code': '33133',
    'country': 'US',
    'state': 'FL',
    'display_address': ['3391 Pan American Dr', 'Miami, FL 33133']},
   'phone': '+13052091200',
   'display_phone': '(305) 209-1200',
   'distance': 6023.917796785677},
  {'id': 'rf9zxndiD2k4hXwBAtQMrQ',
   'alias': 'kpot-korean-bbq-and-hot-pot-miami-2',
   'name': 'KPOT Korean BBQ & Hot Pot',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/UQ65jDW_LSIGuMLEdEACYg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/kpot-korean-bbq-and-hot-pot-miami-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 14,
   'categories': [{'alias': 'korean', 'title': 'Korean'},
    {'alias': 'bbq', 'title': 'Barbeque'},
    {'alias': 'hotpot', 'title': 'Hot Pot'}],
   'rating': 4.7,
   'coordinates': {'latitude': 25.77196, 'longitude': -80.32905},
   'transactions': [],
   'location': {'address1': '8255 W Flagler St',
    'address2': '',
    'address3': None,
    'city': 'Miami',
    'zip_code': '33144',
    'country': 'US',
    'state': 'FL',
    'display_address': ['8255 W Flagler St', 'Miami, FL 33144']},
   'phone': '+17866368137',
   'display_phone': '(786) 636-8137',
   'distance': 4624.134435770181},
  {'id': 'nwY3CmIH75cN85cWBSaOAw',
   'alias': 'apocalypse-bbq-miami',
   'name': 'Apocalypse BBQ',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/dnWRHDwSOApEyxPoZZRFLA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/apocalypse-bbq-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 1153,
   'categories': [{'alias': 'foodtrucks', 'title': 'Food Trucks'},
    {'alias': 'bbq', 'title': 'Barbeque'},
    {'alias': 'empanadas', 'title': 'Empanadas'}],
   'rating': 4.4,
   'coordinates': {'latitude': 25.68797, 'longitude': -80.3936},
   'transactions': [],
   'price': '$$',
   'location': {'address1': '8695 SW 124th Ave',
    'address2': '',
    'address3': None,
    'city': 'Miami',
    'zip_code': '33183',
    'country': 'US',
    'state': 'FL',
    'display_address': ['8695 SW 124th Ave', 'Miami, FL 33183']},
   'phone': '',
   'display_phone': '',
   'distance': 12797.71127183584},
  {'id': 'eVhl0Yu1ZRWRD2D1OQGsYg',
   'alias': 'capriccio-miami-13',
   'name': 'Capriccio',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/XvLWJxAVk_KVc2Ucr5Lh9A/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/capriccio-miami-13?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 170,
   'categories': [{'alias': 'italian', 'title': 'Italian'},
    {'alias': 'pizza', 'title': 'Pizza'},
    {'alias': 'steak', 'title': 'Steakhouses'}],
   'rating': 4.5,
   'coordinates': {'latitude': 25.781633128697905,
    'longitude': -80.28766177465242},
   'transactions': ['restaurant_reservation'],
   'location': {'address1': '5600 Blue Lagoon Dr',
    'address2': 'Ste 9',
    'address3': '',
    'city': 'Miami',
    'zip_code': '33126',
    'country': 'US',
    'state': 'FL',
    'display_address': ['5600 Blue Lagoon Dr', 'Ste 9', 'Miami, FL 33126']},
   'phone': '+17869365470',
   'display_phone': '(786) 936-5470',
   'distance': 3203.121202511091},
  {'id': 'hZm7TunlrksQbgS0ssXbUg',
   'alias': 'versailles-miami-4',
   'name': 'Versailles',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/q_T1_ShhFe0CuPaNtvzLXQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/versailles-miami-4?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 7019,
   'categories': [{'alias': 'cuban', 'title': 'Cuban'},
    {'alias': 'coffee', 'title': 'Coffee & Tea'},
    {'alias': 'sandwiches', 'title': 'Sandwiches'}],
   'rating': 4.0,
   'coordinates': {'latitude': 25.765389817507295,
    'longitude': -80.25287416592283},
   'transactions': ['delivery', 'pickup'],
   'price': '$$',
   'location': {'address1': '3555 SW 8th St',
    'address2': '',
    'address3': '',
    'city': 'Miami',
    'zip_code': '33135',
    'country': 'US',
    'state': 'FL',
    'display_address': ['3555 SW 8th St', 'Miami, FL 33135']},
   'phone': '+13054440240',
   'display_phone': '(305) 444-0240',
   'distance': 3789.5569842271616},
  {'id': 'scZfLg-ujWMEOUmFM_Qalg',
   'alias': 'don-maguey-mexican-restaurant-miami',
   'name': 'Don Maguey Mexican Restaurant',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/emYsWIbH0iMFabrWd3lClQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/don-maguey-mexican-restaurant-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 305,
   'categories': [{'alias': 'mexican', 'title': 'Mexican'}],
   'rating': 4.7,
   'coordinates': {'latitude': 25.7717682877048,
    'longitude': -80.27253760250089},
   'transactions': ['pickup'],
   'price': '$$',
   'location': {'address1': '4747 W Flagler St',
    'address2': '',
    'address3': None,
    'city': 'Miami',
    'zip_code': '33134',
    'country': 'US',
    'state': 'FL',
    'display_address': ['4747 W Flagler St', 'Miami, FL 33134']},
   'phone': '+17865585650',
   'display_phone': '(786) 558-5650',
   'distance': 2616.9735888249156},
  {'id': 'QQnw1bFxLyamuxn4giIy9g',
   'alias': 'sufrat-mediterranean-grill-miami-4',
   'name': 'Sufrat Mediterranean Grill',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/Z5Q7D855uiOO8WKuDn-eGQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/sufrat-mediterranean-grill-miami-4?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 150,
   'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
    {'alias': 'greek', 'title': 'Greek'},
    {'alias': 'lebanese', 'title': 'Lebanese'}],
   'rating': 4.5,
   'coordinates': {'latitude': 25.82001, 'longitude': -80.335628},
   'transactions': ['delivery', 'pickup'],
   'price': '$$',
   'location': {'address1': '8455 NW 53rd St',
    'address2': 'Suite 106',
    'address3': '',
    'city': 'Miami',
    'zip_code': '33166',
    'country': 'US',
    'state': 'FL',
    'display_address': ['8455 NW 53rd St', 'Suite 106', 'Miami, FL 33166']},
   'phone': '+13057987278',
   'display_phone': '(305) 798-7278',
   'distance': 8884.862194544405},
  {'id': 'LPVv4wk9gwGlIEdfZJRaHQ',
   'alias': 'jrk-miami-miami',
   'name': 'Jrk!',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/nB_I7hx4NhhBv5oYF1tDdA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/jrk-miami-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 130,
   'categories': [{'alias': 'caribbean', 'title': 'Caribbean'}],
   'rating': 4.5,
   'coordinates': {'latitude': 25.775205782261285,
    'longitude': -80.19496699999999},
   'transactions': [],
   'price': '$$',
   'location': {'address1': '95 NW 1st St',
    'address2': None,
    'address3': '',
    'city': 'Miami',
    'zip_code': '33128',
    'country': 'US',
    'state': 'FL',
    'display_address': ['95 NW 1st St', 'Miami, FL 33128']},
   'phone': '+13052904684',
   'display_phone': '(305) 290-4684',
   'distance': 9647.891842653617},
  {'id': 'O4gh_gZPp1zW9QtC1aMHWw',
   'alias': 'house-of-food-porn-miami-3',
   'name': 'House of Food Porn',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/YZJP20cFtRP73YEsp69aDA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/house-of-food-porn-miami-3?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 179,
   'categories': [{'alias': 'sushi', 'title': 'Sushi Bars'},
    {'alias': 'asianfusion', 'title': 'Asian Fusion'},
    {'alias': 'wine_bars', 'title': 'Wine Bars'}],
   'rating': 4.8,
   'coordinates': {'latitude': 25.8326319884545,
    'longitude': -80.200107379434},
   'transactions': [],
   'location': {'address1': '197 NW 62nd St',
    'address2': None,
    'address3': '',
    'city': 'Miami',
    'zip_code': '33150',
    'country': 'US',
    'state': 'FL',
    'display_address': ['197 NW 62nd St', 'Miami, FL 33150']},
   'phone': '+13057880137',
   'display_phone': '(305) 788-0137',
   'distance': 12507.730930037038},
  {'id': 'V3btCvWa1flTBYt2YKea_g',
   'alias': 'bombay-darbar-miami-3',
   'name': 'Bombay Darbar',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/ZYRyJ1_iTHzLBr37P78vow/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/bombay-darbar-miami-3?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 1714,
   'categories': [{'alias': 'indpak', 'title': 'Indian'}],
   'rating': 4.5,
   'coordinates': {'latitude': 25.72935, 'longitude': -80.240789},
   'transactions': ['delivery', 'pickup'],
   'price': '$$',
   'location': {'address1': '2901 Florida Ave',
    'address2': '',
    'address3': '',
    'city': 'Miami',
    'zip_code': '33133',
    'country': 'US',
    'state': 'FL',
    'display_address': ['2901 Florida Ave', 'Miami, FL 33133']},
   'phone': '+13054447272',
   'display_phone': '(305) 444-7272',
   'distance': 5405.961958481842},
  {'id': 'gmDna9f57vWTlSrdrEuVEg',
   'alias': 'sanguich-miami',
   'name': 'Sanguich',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/GSYOfiVblSDf68U0wtDsEA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/sanguich-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 1493,
   'categories': [{'alias': 'cuban', 'title': 'Cuban'},
    {'alias': 'sandwiches', 'title': 'Sandwiches'}],
   'rating': 4.5,
   'coordinates': {'latitude': 25.76578005893393, 'longitude': -80.2285558},
   'transactions': ['delivery'],
   'price': '$$',
   'location': {'address1': '2057 SW 8th St',
    'address2': '',
    'address3': None,
    'city': 'Miami',
    'zip_code': '33135',
    'country': 'US',
    'state': 'FL',
    'display_address': ['2057 SW 8th St', 'Miami, FL 33135']},
   'phone': '+13055390969',
   'display_phone': '(305) 539-0969',
   'distance': 6129.703156662285},
  {'id': 'Jjifi324EdbrMWSW2-ZcKQ',
   'alias': 'homa-persian-cuisine-miami',
   'name': 'Homa Persian Cuisine',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/Tf9Lr5KdZavRWCH7qJNFZg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/homa-persian-cuisine-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 40,
   'categories': [{'alias': 'persian', 'title': 'Persian/Iranian'}],
   'rating': 4.8,
   'coordinates': {'latitude': 25.746275, 'longitude': -80.221992},
   'transactions': ['delivery', 'pickup'],
   'location': {'address1': '2490 SW 17th Ave',
    'address2': None,
    'address3': None,
    'city': 'Miami',
    'zip_code': '33145',
    'country': 'US',
    'state': 'FL',
    'display_address': ['2490 SW 17th Ave', 'Miami, FL 33145']},
   'phone': '+13052522222',
   'display_phone': '(305) 252-2222',
   'distance': 6654.565051559707},
  {'id': '_tiVacKyfWZjOljFenLwVQ',
   'alias': 'giselle-miami-miami',
   'name': 'Giselle Miami',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/tMrFekA5lavl0IHHuyVwHg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/giselle-miami-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 496,
   'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
    {'alias': 'lounges', 'title': 'Lounges'},
    {'alias': 'asianfusion', 'title': 'Asian Fusion'}],
   'rating': 4.6,
   'coordinates': {'latitude': 25.78496366, 'longitude': -80.19341399},
   'transactions': [],
   'location': {'address1': '15 NE 11th St',
    'address2': None,
    'address3': '',
    'city': 'Miami',
    'zip_code': '33132',
    'country': 'US',
    'state': 'FL',
    'display_address': ['15 NE 11th St', 'Miami, FL 33132']},
   'phone': '+13053589848',
   'display_phone': '(305) 358-9848',
   'distance': 10127.920790439312},
  {'id': 'wbxKj8E3ucAvky6DuoQZ8g',
   'alias': 'chef-allens-farm-to-table-miami',
   'name': "Chef Allen's Farm to Table",
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/YyKF5ReVYjDkJWJxTbftHw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/chef-allens-farm-to-table-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 14,
   'categories': [{'alias': 'vegetarian', 'title': 'Vegetarian'},
    {'alias': 'foodstands', 'title': 'Food Stands'}],
   'rating': 4.6,
   'coordinates': {'latitude': 25.7869967159839,
    'longitude': -80.1891533285379},
   'transactions': [],
   'price': '$$$',
   'location': {'address1': '263 NE 13th St',
    'address2': '',
    'address3': '',
    'city': 'Miami',
    'zip_code': '33132',
    'country': 'US',
    'state': 'FL',
    'display_address': ['263 NE 13th St', 'Miami, FL 33132']},
   'phone': '',
   'display_phone': '',
   'distance': 10606.989207602253},
  {'id': 'z1UW-zeI50bMEtGKFtrjmA',
   'alias': 'grails-miami-restaurant-and-sports-bar-miami',
   'name': 'Grails Miami - Restaurant & Sports Bar',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/XU08RveGxutYa-B_2qcClQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/grails-miami-restaurant-and-sports-bar-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 774,
   'categories': [{'alias': 'sportsbars', 'title': 'Sports Bars'},
    {'alias': 'newamerican', 'title': 'New American'},
    {'alias': 'lounges', 'title': 'Lounges'}],
   'rating': 4.4,
   'coordinates': {'latitude': 25.803184, 'longitude': -80.195219},
   'transactions': ['delivery', 'pickup'],
   'price': '$$',
   'location': {'address1': '2800 N Miami Ave',
    'address2': None,
    'address3': '',
    'city': 'Miami',
    'zip_code': '33127',
    'country': 'US',
    'state': 'FL',

In [49]:
#Veamos los keys del diccionario recibido
data.keys()

dict_keys(['businesses', 'total', 'region'])

In [50]:
#El primer elemento del diccionario indica el total de restaurants existentes en la API
print('En total la base de datos registra %d restaurants'%data['total'])

En total la base de datos registra 5800 restaurants

In [51]:
data['businesses']

[{'id': 'K3ukx2e11xTRtYBU01dmrA',
  'alias': 'salty-flame-miami',
  'name': 'Salty Flame',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/_6wShTvzfucB5dxFZv4Mpg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/salty-flame-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 258,
  'categories': [{'alias': 'asianfusion', 'title': 'Asian Fusion'},
   {'alias': 'steak', 'title': 'Steakhouses'},
   {'alias': 'cocktailbars', 'title': 'Cocktail Bars'}],
  'rating': 4.3,
  'coordinates': {'latitude': 25.76022, 'longitude': -80.19267},
  'transactions': ['delivery', 'pickup'],
  'location': {'address1': '1414 Brickell Ave',
   'address2': None,
   'address3': '',
   'city': 'Miami',
   'zip_code': '33131',
   'country': 'US',
   'state': 'FL',
   'display_address': ['1414 Brickell Ave', 'Miami, FL 33131']},
  'phone': '+13055638972',
  'display_phone': '(305) 563-8972',
  'distance': 9568.050891007853},
 {'id': 'UXHxLN3DcDGI57uDIfCuJA',
  'alias': 'olds-havana-cuban-bar-and-cocina-miami',
  'name': "Old's Havana Cuban Bar & Cocina",
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/OyMD-xvBjobfDmDdBs2Jfw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/olds-havana-cuban-bar-and-cocina-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 3193,
  'categories': [{'alias': 'cuban', 'title': 'Cuban'},
   {'alias': 'bars', 'title': 'Bars'},
   {'alias': 'venues', 'title': 'Venues & Event Spaces'}],
  'rating': 4.4,
  'coordinates': {'latitude': 25.765607074496565,
   'longitude': -80.21921771559332},
  'transactions': ['pickup', 'restaurant_reservation'],
  'price': '$$',
  'location': {'address1': '1442 SW 8th St',
   'address2': '',
   'address3': None,
   'city': 'Miami',
   'zip_code': '33135',
   'country': 'US',
   'state': 'FL',
   'display_address': ['1442 SW 8th St', 'Miami, FL 33135']},
  'phone': '+17865182196',
  'display_phone': '(786) 518-2196',
  'distance': 7038.216305367002},
 {'id': 'oxtMfBGmVNE18pFVuw7lFg',
  'alias': 'fratellino-coral-gables-2',
  'name': 'Fratellino',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/OPS9ibIzgVyzcJ3ZyNf9IQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/fratellino-coral-gables-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 1899,
  'categories': [{'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.8,
  'coordinates': {'latitude': 25.74917, 'longitude': -80.26011},
  'transactions': ['delivery', 'pickup', 'restaurant_reservation'],
  'price': '$$$',
  'location': {'address1': '264 Miracle Mile',
   'address2': '',
   'address3': '',
   'city': 'Coral Gables',
   'zip_code': '33134',
   'country': 'US',
   'state': 'FL',
   'display_address': ['264 Miracle Mile', 'Coral Gables, FL 33134']},
  'phone': '+17864520068',
  'display_phone': '(786) 452-0068',
  'distance': 2834.064936518243},
 {'id': 'ix8ifP1jQM9ektdVAs19sQ',
  'alias': 'crazy-about-you-miami-3',
  'name': 'Crazy About You',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/C8cICmnvi0GRzr4OIwg6vQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/crazy-about-you-miami-3?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 2883,
  'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
   {'alias': 'italian', 'title': 'Italian'},
   {'alias': 'spanish', 'title': 'Spanish'}],
  'rating': 4.2,
  'coordinates': {'latitude': 25.762015277335745,
   'longitude': -80.1889859201474},
  'transactions': ['delivery'],
  'price': '$$$',
  'location': {'address1': '1155 Brickell Bay Dr',
   'address2': 'Ste 101',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33131',
   'country': 'US',
   'state': 'FL',
   'display_address': ['1155 Brickell Bay Dr', 'Ste 101', 'Miami, FL 33131']},
  'phone': '+13053774442',
  'display_phone': '(305) 377-4442',
  'distance': 9973.468955482575},
 {'id': 'WqIBKxRUPXH3NqTViAHLxQ',
  'alias': 'bayshore-club-bar-and-grill-miami',
  'name': 'Bayshore Club Bar & Grill',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/B7tTbJMlp7Dk6rpE4P3j5Q/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/bayshore-club-bar-and-grill-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 1039,
  'categories': [{'alias': 'seafood', 'title': 'Seafood'},
   {'alias': 'tradamerican', 'title': 'American'},
   {'alias': 'wine_bars', 'title': 'Wine Bars'}],
  'rating': 4.3,
  'coordinates': {'latitude': 25.72877375829567, 'longitude': -80.2341624},
  'transactions': [],
  'price': '$$$',
  'location': {'address1': '3391 Pan American Dr',
   'address2': None,
   'address3': None,
   'city': 'Miami',
   'zip_code': '33133',
   'country': 'US',
   'state': 'FL',
   'display_address': ['3391 Pan American Dr', 'Miami, FL 33133']},
  'phone': '+13052091200',
  'display_phone': '(305) 209-1200',
  'distance': 6023.917796785677},
 {'id': 'rf9zxndiD2k4hXwBAtQMrQ',
  'alias': 'kpot-korean-bbq-and-hot-pot-miami-2',
  'name': 'KPOT Korean BBQ & Hot Pot',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/UQ65jDW_LSIGuMLEdEACYg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/kpot-korean-bbq-and-hot-pot-miami-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 14,
  'categories': [{'alias': 'korean', 'title': 'Korean'},
   {'alias': 'bbq', 'title': 'Barbeque'},
   {'alias': 'hotpot', 'title': 'Hot Pot'}],
  'rating': 4.7,
  'coordinates': {'latitude': 25.77196, 'longitude': -80.32905},
  'transactions': [],
  'location': {'address1': '8255 W Flagler St',
   'address2': '',
   'address3': None,
   'city': 'Miami',
   'zip_code': '33144',
   'country': 'US',
   'state': 'FL',
   'display_address': ['8255 W Flagler St', 'Miami, FL 33144']},
  'phone': '+17866368137',
  'display_phone': '(786) 636-8137',
  'distance': 4624.134435770181},
 {'id': 'nwY3CmIH75cN85cWBSaOAw',
  'alias': 'apocalypse-bbq-miami',
  'name': 'Apocalypse BBQ',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/dnWRHDwSOApEyxPoZZRFLA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/apocalypse-bbq-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 1153,
  'categories': [{'alias': 'foodtrucks', 'title': 'Food Trucks'},
   {'alias': 'bbq', 'title': 'Barbeque'},
   {'alias': 'empanadas', 'title': 'Empanadas'}],
  'rating': 4.4,
  'coordinates': {'latitude': 25.68797, 'longitude': -80.3936},
  'transactions': [],
  'price': '$$',
  'location': {'address1': '8695 SW 124th Ave',
   'address2': '',
   'address3': None,
   'city': 'Miami',
   'zip_code': '33183',
   'country': 'US',
   'state': 'FL',
   'display_address': ['8695 SW 124th Ave', 'Miami, FL 33183']},
  'phone': '',
  'display_phone': '',
  'distance': 12797.71127183584},
 {'id': 'eVhl0Yu1ZRWRD2D1OQGsYg',
  'alias': 'capriccio-miami-13',
  'name': 'Capriccio',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/XvLWJxAVk_KVc2Ucr5Lh9A/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/capriccio-miami-13?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 170,
  'categories': [{'alias': 'italian', 'title': 'Italian'},
   {'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'steak', 'title': 'Steakhouses'}],
  'rating': 4.5,
  'coordinates': {'latitude': 25.781633128697905,
   'longitude': -80.28766177465242},
  'transactions': ['restaurant_reservation'],
  'location': {'address1': '5600 Blue Lagoon Dr',
   'address2': 'Ste 9',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33126',
   'country': 'US',
   'state': 'FL',
   'display_address': ['5600 Blue Lagoon Dr', 'Ste 9', 'Miami, FL 33126']},
  'phone': '+17869365470',
  'display_phone': '(786) 936-5470',
  'distance': 3203.121202511091},
 {'id': 'hZm7TunlrksQbgS0ssXbUg',
  'alias': 'versailles-miami-4',
  'name': 'Versailles',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/q_T1_ShhFe0CuPaNtvzLXQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/versailles-miami-4?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 7019,
  'categories': [{'alias': 'cuban', 'title': 'Cuban'},
   {'alias': 'coffee', 'title': 'Coffee & Tea'},
   {'alias': 'sandwiches', 'title': 'Sandwiches'}],
  'rating': 4.0,
  'coordinates': {'latitude': 25.765389817507295,
   'longitude': -80.25287416592283},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '3555 SW 8th St',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33135',
   'country': 'US',
   'state': 'FL',
   'display_address': ['3555 SW 8th St', 'Miami, FL 33135']},
  'phone': '+13054440240',
  'display_phone': '(305) 444-0240',
  'distance': 3789.5569842271616},
 {'id': 'scZfLg-ujWMEOUmFM_Qalg',
  'alias': 'don-maguey-mexican-restaurant-miami',
  'name': 'Don Maguey Mexican Restaurant',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/emYsWIbH0iMFabrWd3lClQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/don-maguey-mexican-restaurant-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 305,
  'categories': [{'alias': 'mexican', 'title': 'Mexican'}],
  'rating': 4.7,
  'coordinates': {'latitude': 25.7717682877048,
   'longitude': -80.27253760250089},
  'transactions': ['pickup'],
  'price': '$$',
  'location': {'address1': '4747 W Flagler St',
   'address2': '',
   'address3': None,
   'city': 'Miami',
   'zip_code': '33134',
   'country': 'US',
   'state': 'FL',
   'display_address': ['4747 W Flagler St', 'Miami, FL 33134']},
  'phone': '+17865585650',
  'display_phone': '(786) 558-5650',
  'distance': 2616.9735888249156},
 {'id': 'QQnw1bFxLyamuxn4giIy9g',
  'alias': 'sufrat-mediterranean-grill-miami-4',
  'name': 'Sufrat Mediterranean Grill',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/Z5Q7D855uiOO8WKuDn-eGQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/sufrat-mediterranean-grill-miami-4?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 150,
  'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
   {'alias': 'greek', 'title': 'Greek'},
   {'alias': 'lebanese', 'title': 'Lebanese'}],
  'rating': 4.5,
  'coordinates': {'latitude': 25.82001, 'longitude': -80.335628},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '8455 NW 53rd St',
   'address2': 'Suite 106',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33166',
   'country': 'US',
   'state': 'FL',
   'display_address': ['8455 NW 53rd St', 'Suite 106', 'Miami, FL 33166']},
  'phone': '+13057987278',
  'display_phone': '(305) 798-7278',
  'distance': 8884.862194544405},
 {'id': 'LPVv4wk9gwGlIEdfZJRaHQ',
  'alias': 'jrk-miami-miami',
  'name': 'Jrk!',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/nB_I7hx4NhhBv5oYF1tDdA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/jrk-miami-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 130,
  'categories': [{'alias': 'caribbean', 'title': 'Caribbean'}],
  'rating': 4.5,
  'coordinates': {'latitude': 25.775205782261285,
   'longitude': -80.19496699999999},
  'transactions': [],
  'price': '$$',
  'location': {'address1': '95 NW 1st St',
   'address2': None,
   'address3': '',
   'city': 'Miami',
   'zip_code': '33128',
   'country': 'US',
   'state': 'FL',
   'display_address': ['95 NW 1st St', 'Miami, FL 33128']},
  'phone': '+13052904684',
  'display_phone': '(305) 290-4684',
  'distance': 9647.891842653617},
 {'id': 'O4gh_gZPp1zW9QtC1aMHWw',
  'alias': 'house-of-food-porn-miami-3',
  'name': 'House of Food Porn',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/YZJP20cFtRP73YEsp69aDA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/house-of-food-porn-miami-3?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 179,
  'categories': [{'alias': 'sushi', 'title': 'Sushi Bars'},
   {'alias': 'asianfusion', 'title': 'Asian Fusion'},
   {'alias': 'wine_bars', 'title': 'Wine Bars'}],
  'rating': 4.8,
  'coordinates': {'latitude': 25.8326319884545, 'longitude': -80.200107379434},
  'transactions': [],
  'location': {'address1': '197 NW 62nd St',
   'address2': None,
   'address3': '',
   'city': 'Miami',
   'zip_code': '33150',
   'country': 'US',
   'state': 'FL',
   'display_address': ['197 NW 62nd St', 'Miami, FL 33150']},
  'phone': '+13057880137',
  'display_phone': '(305) 788-0137',
  'distance': 12507.730930037038},
 {'id': 'V3btCvWa1flTBYt2YKea_g',
  'alias': 'bombay-darbar-miami-3',
  'name': 'Bombay Darbar',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/ZYRyJ1_iTHzLBr37P78vow/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/bombay-darbar-miami-3?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 1714,
  'categories': [{'alias': 'indpak', 'title': 'Indian'}],
  'rating': 4.5,
  'coordinates': {'latitude': 25.72935, 'longitude': -80.240789},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '2901 Florida Ave',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33133',
   'country': 'US',
   'state': 'FL',
   'display_address': ['2901 Florida Ave', 'Miami, FL 33133']},
  'phone': '+13054447272',
  'display_phone': '(305) 444-7272',
  'distance': 5405.961958481842},
 {'id': 'gmDna9f57vWTlSrdrEuVEg',
  'alias': 'sanguich-miami',
  'name': 'Sanguich',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/GSYOfiVblSDf68U0wtDsEA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/sanguich-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 1493,
  'categories': [{'alias': 'cuban', 'title': 'Cuban'},
   {'alias': 'sandwiches', 'title': 'Sandwiches'}],
  'rating': 4.5,
  'coordinates': {'latitude': 25.76578005893393, 'longitude': -80.2285558},
  'transactions': ['delivery'],
  'price': '$$',
  'location': {'address1': '2057 SW 8th St',
   'address2': '',
   'address3': None,
   'city': 'Miami',
   'zip_code': '33135',
   'country': 'US',
   'state': 'FL',
   'display_address': ['2057 SW 8th St', 'Miami, FL 33135']},
  'phone': '+13055390969',
  'display_phone': '(305) 539-0969',
  'distance': 6129.703156662285},
 {'id': 'Jjifi324EdbrMWSW2-ZcKQ',
  'alias': 'homa-persian-cuisine-miami',
  'name': 'Homa Persian Cuisine',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/Tf9Lr5KdZavRWCH7qJNFZg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/homa-persian-cuisine-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 40,
  'categories': [{'alias': 'persian', 'title': 'Persian/Iranian'}],
  'rating': 4.8,
  'coordinates': {'latitude': 25.746275, 'longitude': -80.221992},
  'transactions': ['delivery', 'pickup'],
  'location': {'address1': '2490 SW 17th Ave',
   'address2': None,
   'address3': None,
   'city': 'Miami',
   'zip_code': '33145',
   'country': 'US',
   'state': 'FL',
   'display_address': ['2490 SW 17th Ave', 'Miami, FL 33145']},
  'phone': '+13052522222',
  'display_phone': '(305) 252-2222',
  'distance': 6654.565051559707},
 {'id': '_tiVacKyfWZjOljFenLwVQ',
  'alias': 'giselle-miami-miami',
  'name': 'Giselle Miami',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/tMrFekA5lavl0IHHuyVwHg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/giselle-miami-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 496,
  'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
   {'alias': 'lounges', 'title': 'Lounges'},
   {'alias': 'asianfusion', 'title': 'Asian Fusion'}],
  'rating': 4.6,
  'coordinates': {'latitude': 25.78496366, 'longitude': -80.19341399},
  'transactions': [],
  'location': {'address1': '15 NE 11th St',
   'address2': None,
   'address3': '',
   'city': 'Miami',
   'zip_code': '33132',
   'country': 'US',
   'state': 'FL',
   'display_address': ['15 NE 11th St', 'Miami, FL 33132']},
  'phone': '+13053589848',
  'display_phone': '(305) 358-9848',
  'distance': 10127.920790439312},
 {'id': 'wbxKj8E3ucAvky6DuoQZ8g',
  'alias': 'chef-allens-farm-to-table-miami',
  'name': "Chef Allen's Farm to Table",
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/YyKF5ReVYjDkJWJxTbftHw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/chef-allens-farm-to-table-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 14,
  'categories': [{'alias': 'vegetarian', 'title': 'Vegetarian'},
   {'alias': 'foodstands', 'title': 'Food Stands'}],
  'rating': 4.6,
  'coordinates': {'latitude': 25.7869967159839,
   'longitude': -80.1891533285379},
  'transactions': [],
  'price': '$$$',
  'location': {'address1': '263 NE 13th St',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33132',
   'country': 'US',
   'state': 'FL',
   'display_address': ['263 NE 13th St', 'Miami, FL 33132']},
  'phone': '',
  'display_phone': '',
  'distance': 10606.989207602253},
 {'id': 'z1UW-zeI50bMEtGKFtrjmA',
  'alias': 'grails-miami-restaurant-and-sports-bar-miami',
  'name': 'Grails Miami - Restaurant & Sports Bar',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/XU08RveGxutYa-B_2qcClQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/grails-miami-restaurant-and-sports-bar-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 774,
  'categories': [{'alias': 'sportsbars', 'title': 'Sports Bars'},
   {'alias': 'newamerican', 'title': 'New American'},
   {'alias': 'lounges', 'title': 'Lounges'}],
  'rating': 4.4,
  'coordinates': {'latitude': 25.803184, 'longitude': -80.195219},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '2800 N Miami Ave',
   'address2': None,
   'address3': '',
   'city': 'Miami',
   'zip_code': '33127',
   'country': 'US',
   'state': 'FL',
   'display_address': ['2800 N Miami Ave', 'Miami, FL 33127']},
  'phone': '+17868704313',
  'display_phone': '(786) 870-4313',
  'distance': 10852.71572211731},
 {'id': '0FRl-hghB50Gw3CQnasq2Q',
  'alias': 'braga-portuguese-restaurant-miami',
  'name': 'Braga Portuguese Restaurant',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/1dW7NRwqtuafcvRd2LBcfg/o.jpg',
  'is_closed': False,

In [52]:
#Convertimos los datos elegidos a una Data Frame

df_yelp = pd.DataFrame(data["businesses"])

print("Visualización de la tabla de Miami")
display(df_yelp.head())

Visualización de la tabla de Miami

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,location,phone,display_phone,distance,price
0,K3ukx2e11xTRtYBU01dmrA,salty-flame-miami,Salty Flame,https://s3-media0.fl.yelpcdn.com/bphoto/_6wShT...,False,https://www.yelp.com/biz/salty-flame-miami?adj...,258,"[{'alias': 'asianfusion', 'title': 'Asian Fusi...",4.3,"{'latitude': 25.76022, 'longitude': -80.19267}","[delivery, pickup]","{'address1': '1414 Brickell Ave', 'address2': ...",+13055638972,(305) 563-8972,9568.050891,NaN
1,UXHxLN3DcDGI57uDIfCuJA,olds-havana-cuban-bar-and-cocina-miami,Old's Havana Cuban Bar & Cocina,https://s3-media0.fl.yelpcdn.com/bphoto/OyMD-x...,False,https://www.yelp.com/biz/olds-havana-cuban-bar...,3193,"[{'alias': 'cuban', 'title': 'Cuban'}, {'alias...",4.4,"{'latitude': 25.765607074496565, 'longitude': ...","[pickup, restaurant_reservation]","{'address1': '1442 SW 8th St', 'address2': '',...",+17865182196,(786) 518-2196,7038.216305,$$
2,oxtMfBGmVNE18pFVuw7lFg,fratellino-coral-gables-2,Fratellino,https://s3-media0.fl.yelpcdn.com/bphoto/OPS9ib...,False,https://www.yelp.com/biz/fratellino-coral-gabl...,1899,"[{'alias': 'italian', 'title': 'Italian'}]",4.8,"{'latitude': 25.74917, 'longitude': -80.26011}","[delivery, pickup, restaurant_reservation]","{'address1': '264 Miracle Mile', 'address2': '...",+17864520068,(786) 452-0068,2834.064937,$$$
3,ix8ifP1jQM9ektdVAs19sQ,crazy-about-you-miami-3,Crazy About You,https://s3-media0.fl.yelpcdn.com/bphoto/C8cICm...,False,https://www.yelp.com/biz/crazy-about-you-miami...,2883,"[{'alias': 'mediterranean', 'title': 'Mediterr...",4.2,"{'latitude': 25.762015277335745, 'longitude': ...",[delivery],"{'address1': '1155 Brickell Bay Dr', 'address2...",+13053774442,(305) 377-4442,9973.468955,$$$
4,WqIBKxRUPXH3NqTViAHLxQ,bayshore-club-bar-and-grill-miami,Bayshore Club Bar & Grill,https://s3-media0.fl.yelpcdn.com/bphoto/B7tTbJ...,False,https://www.yelp.com/biz/bayshore-club-bar-and...,1039,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",4.3,"{'latitude': 25.72877375829567, 'longitude': -...",[],"{'address1': '3391 Pan American Dr', 'address2...",+13052091200,(305) 209-1200,6023.917797,$$$

#### <span style="color:#00b6ff">**Normalización de datos**</span>

In [53]:
#Se normalizan los datos para poder limpiarlos después

df_plano = pd.json_normalize(data["businesses"])

In [54]:
#Se definen nuevas columnas ordenadas
df_final = df_plano[[
    "name",
    "review_count",
    "rating",
    "location.city",
    "location.zip_code",
    "price"
]].copy()

#Cambiamos los nombres para que quede más legible

df_final.columns = ["Nombre", "Reseñas", "Calificación", "Ciudad", "CP", "Precio"]

display(df_final.head())

,Nombre,Reseñas,Calificación,Ciudad,CP,Precio
0,Salty Flame,258,4.3,Miami,33131,NaN
1,Old's Havana Cuban Bar & Cocina,3193,4.4,Miami,33135,$$
2,Fratellino,1899,4.8,Coral Gables,33134,$$$
3,Crazy About You,2883,4.2,Miami,33131,$$$
4,Bayshore Club Bar & Grill,1039,4.3,Miami,33133,$$$

#### <span style="color:#00b6ff">**Limpieza de datos de la API**</span>

In [55]:
print(df_final.isnull().sum())
print(f"\nShape: {df_final.shape}")
print(f"\nTipos de datos:\n{df_final.dtypes}")

Nombre           0
Reseñas          0
Calificación     0
Ciudad           0
CP               0
Precio          16
dtype: int64

Shape: (50, 6)

Tipos de datos:
Nombre           object
Reseñas           int64
Calificación    float64
Ciudad           object
CP               object
Precio           object
dtype: object

In [63]:
# Limpieza df_final
moda_precio = df_final['Precio'].mode()[0]
df_final['Precio'] = df_final['Precio'].fillna(moda_precio)

# Verificación
print(f"✅ Nulos en Precio imputados con: '{moda_precio}'")
print(df_final.isnull().sum())
print(f"Shape: {df_final.shape}")

✅ Nulos en Precio imputados con: '$$'
Nombre          0
Reseñas         0
Calificación    0
Ciudad          0
CP              0
Precio          0
dtype: int64
Shape: (50, 6)

#### <span style="color:#00b6ff">**Integración**</span>

#### _Se realiza la integración desde la ciudad, en este caso Miami_

In [64]:
#Utilizamos Merge para unir los resultados del análisis EDA con el filtrado de la API YELP

df_integrado = pd.merge(
    df_clientes, 
    df_final, 
    left_on="ciudad_residencia", 
    right_on="Ciudad", 
    how="left"
)

print("Integración correcta")
print(f"Nuevas columnas añadidas: {df_final.columns.tolist()}")
display(df_integrado.head())

Integración correcta
Nuevas columnas añadidas: ['Nombre', 'Reseñas', 'Calificación', 'Ciudad', 'CP', 'Precio']

,id_persona,nombre,apellido,edad,genero,ciudad_residencia,estrato_socioeconomico,frecuencia_visita,promedio_gasto_comida,ocio,consume_licor,preferencias_alimenticias,membresia_premium,tipo_de_pago_mas_usado,ingresos_mensuales,rango_etario,Nombre,Reseñas,Calificación,Ciudad,CP,Precio
0,2550327378,Jackson,Gomez,31.0,Masculino,Miami,Alto,6,67.51,Sí,No,Vegetariano,Sí,Efectivo,6425,26-35,Salty Flame,258,4.3,Miami,33131,$$
1,2550327378,Jackson,Gomez,31.0,Masculino,Miami,Alto,6,67.51,Sí,No,Vegetariano,Sí,Efectivo,6425,26-35,Old's Havana Cuban Bar & Cocina,3193,4.4,Miami,33135,$$
2,2550327378,Jackson,Gomez,31.0,Masculino,Miami,Alto,6,67.51,Sí,No,Vegetariano,Sí,Efectivo,6425,26-35,Crazy About You,2883,4.2,Miami,33131,$$$
3,2550327378,Jackson,Gomez,31.0,Masculino,Miami,Alto,6,67.51,Sí,No,Vegetariano,Sí,Efectivo,6425,26-35,Bayshore Club Bar & Grill,1039,4.3,Miami,33133,$$$
4,2550327378,Jackson,Gomez,31.0,Masculino,Miami,Alto,6,67.51,Sí,No,Vegetariano,Sí,Efectivo,6425,26-35,KPOT Korean BBQ & Hot Pot,14,4.7,Miami,33144,$$

#### <span style="color:#00b6ff">**Limpieza de datos**</span>

#### _Valores nulos_

In [72]:
#Cantidad totales de valores nulos 
#Tamaño total de la tabla

print(f"Tamaño total de la tabla: {df_integrado.shape}")
print("Valores nulos por columna:")
print(df_integrado.isnull().sum())

Tamaño total de la tabla: (34271, 22)
Valores nulos por columna:
id_persona                     0
nombre                         0
apellido                       0
edad                           0
genero                         0
ciudad_residencia              0
estrato_socioeconomico         0
frecuencia_visita              0
promedio_gasto_comida          0
ocio                           0
consume_licor                  0
preferencias_alimenticias      0
membresia_premium              0
tipo_de_pago_mas_usado         0
ingresos_mensuales             0
rango_etario                 473
Nombre                         0
Reseñas                        0
Calificación                   0
Ciudad                         0
CP                             0
Precio                         0
dtype: int64

In [73]:
df_integrado['rango_etario'] = df_integrado['rango_etario'].fillna('No especifica')
print(f"Tamaño total de la tabla: {df_integrado.shape}")
print("Valores nulos por columna:")
print(df_integrado.isnull().sum())

Tamaño total de la tabla: (34271, 22)
Valores nulos por columna:
id_persona                   0
nombre                       0
apellido                     0
edad                         0
genero                       0
ciudad_residencia            0
estrato_socioeconomico       0
frecuencia_visita            0
promedio_gasto_comida        0
ocio                         0
consume_licor                0
preferencias_alimenticias    0
membresia_premium            0
tipo_de_pago_mas_usado       0
ingresos_mensuales           0
rango_etario                 0
Nombre                       0
Reseñas                      0
Calificación                 0
Ciudad                       0
CP                           0
Precio                       0
dtype: int64

#### <span style="color:#00b6ff">**Filtrado de datos**</span>

#### _A continuación buscaremos los mejores restaurantes en Miami (según la calificación y un número de reseñas) y los mejores clientes (según el gasto promedio y el poder adquisitivo)_

In [74]:

df_miami_limpio = df_integrado.copy()

df_top_resto = df_miami_limpio[
    (df_miami_limpio["Calificación"] >= 4.0) & 
    (df_miami_limpio["Reseñas"] > 50)
]

#Buscamos a los clientes que tiene el ingreso por encima del 50%
umbral_ingresos = df_miami_limpio["ingresos_mensuales"].median()
df_objetivo = df_top_resto[df_top_resto["ingresos_mensuales"] >= umbral_ingresos]

print(f"Estos son la cantidad total de combinaciones ideales (cliente-restaurante): {df_objetivo.shape[0]}")

Estos son la cantidad total de combinaciones ideales (cliente-restaurante): 13965

#### <span style="color:#00b6ff">**Recomendaciones**</span>

#### _Estos son los 10 restaurantes recomendados para nuestros clientes objetivo_

In [75]:
recomendados = df_objetivo[["Nombre", "Calificación", "Reseñas", "Precio"]].drop_duplicates()

recomendados_ranking = recomendados.sort_values(by=["Calificación", "Reseñas"], ascending=False)

print("Los 10 mejores restaurantes para nuestros clientes en Miami:")
display(recomendados_ranking.head(10))

Los 10 mejores restaurantes para nuestros clientes en Miami:

                           Nombre  Calificación  Reseñas Precio
54             House of Food Porn           4.8      179     $$
61    Braga Portuguese Restaurant           4.8       80     $$
62           Good Chef Restaurant           4.7      771     $$
75                     Sweet Dogs           4.7      760      $
68       Certo Italian Restaurant           4.7      425     $$
51  Don Maguey Mexican Restaurant           4.7      305     $$
76                    Mint Beirut           4.7       84     $$
58                  Giselle Miami           4.6      496     $$
72                      107 Taste           4.6      256     $$
71              Dumplings Mi Amor           4.6      131     $$

#### <span style="color:#00b6ff">**Conclusiones**</span>

#### _En el avance 1 se buscó segmentar los mejores clientes (los que más consumían en la ciudad de Miami). El público objetivo son personas de ambos sexos, de 46 años en adelantes de la ciudad de Miami y con el poder adquisitivo muy alto, para obtener los mejores resultados en sus campañas publicitarias, ya que son éstos los clientes que mayor consumo generan en el restaurante. Al haber cruzado estos datos con los restaurantes con mayor calificación y reseña, hemos determinado las 10 mejores opciones para el equipo de marketing, en otras palabras, las campañas tienen que ser dirigidas a esa población y en esos establecimientos mencionados arriba._